# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

networks:
  public:  
    name: public
    driver: bridge
  private:
    name: private
    driver: bridge

services:
  customerwebapi:
    container_name: webapi_container
    image: customerwebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    environment:
      - DB_HOST=mysql_database
      - DB_NAME=${MYSQL_DB_NAME}
      - DB_USER=${MYSQL_DB_USER}
      - DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - DB_PORT=3306
    networks:
      - public
      - private
    depends_on:
      - mysql_database  
  
  mysql_database:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_DB_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - private