### Get all objects 
GET http://localhost:80/api/NoRelational/GetObjects HTTP/1.1

### Get all no relational objects 
GET http://localhost:80/api/NoRelational/GetNoRelationalObjects HTTP/1.1

### Add object
POST http://localhost:80/api/NoRelational/AddObject HTTP/1.1
Content-Type: application/json

{
    "Id": 0,
    "Name": "Obj 0",
    "Value": "0",
    "ParentId": -1
}

### Delete object
DELETE http://localhost:80/api/NoRelational/DeleteObject/7 HTTP/1.1

### Update object
PUT http://localhost:80/api/NoRelational/UpdateObject HTTP/1.1
Content-Type: application/json

{
    "Id": 8,
    "Name": "OCHO",
    "Value": "8",
    "ParentId": 7
}