apiVersion: v1
kind: Service
metadata:
  name: backend2-service
spec:
  type: ClusterIP # default
  selector:
    component: backend2
  ports:
  - port: 5001
    targetPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend2
  template:
    metadata:
      labels:
        component: backend2
    spec:
      containers:
      - name: dotnet-backend2
        image: k8s-dotnet-backend2:v1
        #imagePullPolicy: Never  # prevent pulling image from docker hub
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "64Mi"
            cpu: "128m"
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: MYSQL_DB_NAME
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MYSQL_ROOT_PASSWORD
        - name: DB_PORT
          value: "3306"