apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
spec:
  type: ClusterIP # default
  selector:
    component: web
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: angular-frontend
        image: k8s-angular-frontend:v1
        #imagePullPolicy: Never  # prevent pulling image from docker hub
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "64Mi"
            cpu: "128m"
        ports:
        - containerPort: 80