apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  type: ClusterIP
  selector:
    component: mssql
  ports:
  - port: 1433
    targetPort: 1433

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mssql
  template:
    metadata:
      labels:
        component: mssql
    spec:
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim
      containers:
      - name: mssql-deployment
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "256m"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/lib/mssql/data
          subPath: mssql-data
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MSSQL_DB_PASSWORD
        - name: MSSQL_PID
          value: "Express"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  labels:
    app: mssql
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce